"""Add replying_to to handle study room chat replying

Revision ID: 3ffe256be640
Revises: 6a4af1554ebc
Create Date: 2026-05-10 20:03:03.901871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ffe256be640'
down_revision: Union[str, Sequence[str], None] = '6a4af1554ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_room_messages', sa.Column('replying_to', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('study_room_messages_replying_to_fkey'), 'study_room_messages', 'study_room_messages', ['replying_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('study_room_messages_replying_to_fkey'), 'study_room_messages', type_='foreignkey')
    op.drop_column('study_room_messages', 'replying_to')
    # ### end Alembic commands ###