"""Add streak tracker field on user model

Revision ID: 378a3306d56a
Revises: 61175e23b736
Create Date: 2026-04-08 11:45:01.945028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '378a3306d56a'
down_revision: Union[str, Sequence[str], None] = '61175e23b736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False))
    op.alter_column('users', 'total_xp',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'total_xp',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('users', 'longest_streak')
    op.drop_column('users', 'current_streak')
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###