"""Add source id to certificates model

Revision ID: 4a95c9836521
Revises: 17f1735c4c95
Create Date: 2026-04-22 18:59:44.687854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4a95c9836521'
down_revision: Union[str, Sequence[str], None] = '17f1735c4c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certificates', sa.Column('source_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificates', 'source_id')
    # ### end Alembic commands ###