"""Add user login history table

Revision ID: 0c010a04ced0
Revises: 82bd0b7ddc97
Create Date: 2026-07-16 21:17:11.445160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0c010a04ced0'
down_revision: Union[str, Sequence[str], None] = '82bd0b7ddc97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userloginhistory',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('userloginhistory_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('userloginhistory_pkey'))
    )
    op.create_index(op.f('userloginhistory_id_idx'), 'userloginhistory', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('userloginhistory_id_idx'), table_name='userloginhistory')
    op.drop_table('userloginhistory')
    # ### end Alembic commands ###