"""Create task table

Revision ID: dee9f8fa2670
Revises: 2e0f625c14d8
Create Date: 2026-04-08 13:09:09.123105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dee9f8fa2670'
down_revision: Union[str, Sequence[str], None] = '2e0f625c14d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('progress', sa.String(), server_default='Todo', nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('task_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('task_pkey'))
    )
    op.create_index(op.f('task_user_id_idx'), 'task', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('task_user_id_idx'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###