"""Implement initial community module database models

Revision ID: c0542e59e147
Revises: 251a700ee9d7
Create Date: 2026-04-15 11:23:44.274656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c0542e59e147'
down_revision: Union[str, Sequence[str], None] = '251a700ee9d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('forum_posts_author_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('forum_posts_pkey'))
    )
    op.create_index(op.f('forum_posts_author_id_idx'), 'forum_posts', ['author_id'], unique=False)
    op.create_table('study_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('study_rooms_author_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('study_rooms_pkey'))
    )
    op.create_table('forum_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('forum_comments_author_id_fkey')),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], name=op.f('forum_comments_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('forum_comments_pkey'))
    )
    op.create_index(op.f('forum_comments_post_id_idx'), 'forum_comments', ['post_id'], unique=False)
    op.create_table('forum_post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['forum_posts.id'], name=op.f('forum_post_likes_post_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('forum_post_likes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('forum_post_likes_pkey'))
    )
    op.create_index(op.f('forum_post_likes_post_id_idx'), 'forum_post_likes', ['post_id'], unique=False)
    op.create_table('study_room_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('study_room_messages_author_id_fkey')),
    sa.ForeignKeyConstraint(['room_id'], ['study_rooms.id'], name=op.f('study_room_messages_room_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('study_room_messages_pkey'))
    )
    op.create_index(op.f('study_room_messages_room_id_idx'), 'study_room_messages', ['room_id'], unique=False)
    op.create_table('study_room_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['study_rooms.id'], name=op.f('study_room_participants_room_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('study_room_participants_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('study_room_participants_pkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('study_room_participants')
    op.drop_index(op.f('study_room_messages_room_id_idx'), table_name='study_room_messages')
    op.drop_table('study_room_messages')
    op.drop_index(op.f('forum_post_likes_post_id_idx'), table_name='forum_post_likes')
    op.drop_table('forum_post_likes')
    op.drop_index(op.f('forum_comments_post_id_idx'), table_name='forum_comments')
    op.drop_table('forum_comments')
    op.drop_table('study_rooms')
    op.drop_index(op.f('forum_posts_author_id_idx'), table_name='forum_posts')
    op.drop_table('forum_posts')
    # ### end Alembic commands ###