"""Make NIM nullable

Revision ID: 31b2d48e71df
Revises: def5c16e8529
Create Date: 2026-04-11 08:01:01.313186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31b2d48e71df'
down_revision: Union[str, Sequence[str], None] = 'def5c16e8529'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('users_nim_idx', table_name='users')
    op.create_unique_constraint(op.f('users_nim_key'), 'users', ['nim'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_nim_key'), 'users', type_='unique')
    op.create_index('users_nim_idx', 'users', ['nim'], unique=True)
    # ### end Alembic commands ###