"""add user fields

Revision ID: 2c93e4918134
Revises: afa4a03348cb
Create Date: 2026-04-03 15:25:20.531988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c93e4918134'
down_revision: Union[str, Sequence[str], None] = 'afa4a03348cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('nim', sa.String(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.create_index(op.f('users_nim_idx'), 'users', ['nim'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('users_nim_idx'), table_name='users')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'full_name')
    op.drop_column('users', 'nim')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###