"""Support soft deletion of post and study room

Revision ID: 4bb6d5ad0b2e
Revises: dba6b23e5bcd
Create Date: 2026-06-14 14:02:58.653323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4bb6d5ad0b2e'
down_revision: Union[str, Sequence[str], None] = 'dba6b23e5bcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_posts', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('study_rooms', sa.Column('deleted', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('idx_userquest_user_frequency'), table_name='userquest')
    op.drop_index(op.f('idx_rank_lookup'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_rank_lookup'), 'users', ['share_leaderboard_stats', sa.literal_column('total_xp DESC'), 'full_name'], unique=False)
    op.create_index(op.f('idx_userquest_user_frequency'), 'userquest', ['user_id', 'frequency'], unique=False)
    op.drop_column('study_rooms', 'deleted')
    op.drop_column('forum_posts', 'deleted')
    # ### end Alembic commands ###