"""Add forum category to forum post

Revision ID: ed36e980c670
Revises: b141fee73d96
Create Date: 2026-04-22 10:27:18.693374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ed36e980c670'
down_revision: Union[str, Sequence[str], None] = 'b141fee73d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_posts', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('forum_posts', 'category')
    # ### end Alembic commands ###