"""Implement quiz module database models

Revision ID: c24d79b540b7
Revises: ed36e980c670
Create Date: 2026-04-22 14:28:38.160225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c24d79b540b7'
down_revision: Union[str, Sequence[str], None] = 'ed36e980c670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('minimum_score', sa.Integer(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('quizzes_pkey'))
    )
    op.create_index(op.f('quizzes_category_idx'), 'quizzes', ['category'], unique=False)
    op.create_index(op.f('quizzes_title_idx'), 'quizzes', ['title'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('minimum_score', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('points_gained', sa.Integer(), nullable=False),
    sa.Column('streak_bonus', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('quiz_attempts_quiz_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('quiz_attempts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_attempts_pkey'))
    )
    op.create_index(op.f('quiz_attempts_certificate_id_idx'), 'quiz_attempts', ['certificate_id'], unique=False)
    op.create_index(op.f('quiz_attempts_quiz_id_idx'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('quiz_attempts_user_id_idx'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('option_a', sa.Text(), nullable=False),
    sa.Column('option_b', sa.Text(), nullable=False),
    sa.Column('option_c', sa.Text(), nullable=False),
    sa.Column('option_d', sa.Text(), nullable=False),
    sa.Column('correct_option', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name=op.f('quiz_questions_quiz_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_questions_pkey'))
    )
    op.create_index(op.f('quiz_questions_order_index_idx'), 'quiz_questions', ['order_index'], unique=False)
    op.create_index(op.f('quiz_questions_quiz_id_idx'), 'quiz_questions', ['quiz_id'], unique=False)
    op.create_table('quiz_attempt_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], name=op.f('quiz_attempt_answers_attempt_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], name=op.f('quiz_attempt_answers_question_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_attempt_answers_pkey'))
    )
    op.create_index(op.f('quiz_attempt_answers_attempt_id_idx'), 'quiz_attempt_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('quiz_attempt_answers_question_id_idx'), 'quiz_attempt_answers', ['question_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('quiz_attempt_answers_question_id_idx'), table_name='quiz_attempt_answers')
    op.drop_index(op.f('quiz_attempt_answers_attempt_id_idx'), table_name='quiz_attempt_answers')
    op.drop_table('quiz_attempt_answers')
    op.drop_index(op.f('quiz_questions_quiz_id_idx'), table_name='quiz_questions')
    op.drop_index(op.f('quiz_questions_order_index_idx'), table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index(op.f('quiz_attempts_user_id_idx'), table_name='quiz_attempts')
    op.drop_index(op.f('quiz_attempts_quiz_id_idx'), table_name='quiz_attempts')
    op.drop_index(op.f('quiz_attempts_certificate_id_idx'), table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('quizzes_title_idx'), table_name='quizzes')
    op.drop_index(op.f('quizzes_category_idx'), table_name='quizzes')
    op.drop_table('quizzes')
    # ### end Alembic commands ###