"""Implement individual room chat liking

Revision ID: ee606155f585
Revises: 81383d351fc7
Create Date: 2026-05-10 19:02:17.449537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee606155f585'
down_revision: Union[str, Sequence[str], None] = '81383d351fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_chat_likes',
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['study_room_messages.id'], name=op.f('room_chat_likes_chat_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('room_chat_likes_user_id_fkey')),
    sa.PrimaryKeyConstraint('chat_id', 'user_id', name=op.f('room_chat_likes_pkey'))
    )
    op.create_index(op.f('room_chat_likes_chat_id_idx'), 'room_chat_likes', ['chat_id'], unique=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('room_chat_likes_chat_id_idx'), table_name='room_chat_likes')
    op.drop_table('room_chat_likes')
    # ### end Alembic commands ###