"""Update quest history to new quest table

Revision ID: 899012018bc8
Revises: 0c010a04ced0
Create Date: 2026-07-16 22:30:27.940243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '899012018bc8'
down_revision: Union[str, Sequence[str], None] = '0c010a04ced0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('questhistory_quest_id_idx'), 'questhistory', ['quest_id'], unique=False)
    op.create_foreign_key(op.f('questhistory_quest_id_fkey'), 'questhistory', 'quests', ['quest_id'], ['id'], ondelete='CASCADE')
    op.alter_column('userloginhistory', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userloginhistory', 'date',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint(op.f('questhistory_quest_id_fkey'), 'questhistory', type_='foreignkey')
    op.drop_index(op.f('questhistory_quest_id_idx'), table_name='questhistory')
    # ### end Alembic commands ###