"""Add unique username to user table

Revision ID: 81383d351fc7
Revises: e85c9432b3aa
Create Date: 2026-05-10 16:16:11.866774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81383d351fc7'
down_revision: Union[str, Sequence[str], None] = 'e85c9432b3aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # auto generate existing user username based on their fullname
    op.add_column('users', sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    bind = op.get_bind()
    session = sa.orm.Session(bind=bind)
    users = bind.execute(sa.text("SELECT id, full_name FROM users")).fetchall()
    
    used_usernames = set()

    for user_id, full_name in users:
        base_name = "".join(c for c in full_name if c.isalnum() or c.isspace()).strip().lower().replace(" ", "_")

        username = base_name
        counter = 1
        
        # add suffix for duplicated username
        while username in used_usernames:
            username = f"{base_name}{counter}"
            counter += 1
        
        used_usernames.add(username)

        bind.execute(
            sa.text("UPDATE users SET user_name = :uname WHERE id = :uid"),
            {"uname": username, "uid": user_id}
        )
    op.alter_column('users', 'user_name', nullable=False)
    op.create_unique_constraint(op.f('users_user_name_key'), 'users', ['user_name'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_user_name_key'), 'users', type_='unique')
    op.drop_column('users', 'user_name')
    # ### end Alembic commands ###