"""Add competed_at field on task model

Revision ID: 77f882ecc65f
Revises: a2ed1b1b72d7
Create Date: 2026-04-30 09:05:31.688547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '77f882ecc65f'
down_revision: Union[str, Sequence[str], None] = 'a2ed1b1b72d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('forum_post_likes', sa.Column('like', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('task', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'completed_at')
    op.drop_column('forum_post_likes', 'like')
    # ### end Alembic commands ###