"""Add share leaderboard setting field to db

Revision ID: e85c9432b3aa
Revises: 235ba0bd053f
Create Date: 2026-05-05 08:52:23.430367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e85c9432b3aa'
down_revision: Union[str, Sequence[str], None] = '235ba0bd053f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('share_leaderboard_stats', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET share_leaderboard_stats = true")
    op.alter_column('users', 'share_leaderboard_stats', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'share_leaderboard_stats')
    # ### end Alembic commands ###