"""Add notification setting field to db

Revision ID: 235ba0bd053f
Revises: 77f882ecc65f
Create Date: 2026-05-04 10:38:16.901138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '235ba0bd053f'
down_revision: Union[str, Sequence[str], None] = '77f882ecc65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # nullable first -> set false -> non nullable again
    op.add_column('users', sa.Column('notification_on', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET notification_on = false")
    op.alter_column('users', 'notification_on', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_on')
    # ### end Alembic commands ###