"""Implement friend models

Revision ID: a699d3c51cc3
Revises: 3ffe256be640
Create Date: 2026-05-11 11:33:18.641784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a699d3c51cc3'
down_revision: Union[str, Sequence[str], None] = '3ffe256be640'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('requested_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['requested_id'], ['users.id'], name=op.f('friendships_requested_id_fkey')),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('friendships_requester_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('friendships_pkey'))
    )
    op.create_index('unique_friendship_pair', 'friendships', [sa.literal_column('least(requester_id, requested_id)'), sa.literal_column('greatest(requester_id, requested_id)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_friendship_pair', table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###