"""Create per-user achievement and quest tracking table

Revision ID: ded2692250e7
Revises: 2c93e4918134
Create Date: 2026-04-08 09:05:11.436204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ded2692250e7'
down_revision: Union[str, Sequence[str], None] = '2c93e4918134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userachievement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('achievement_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('userachievement_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('userachievement_pkey'))
    )
    op.create_index(op.f('userachievement_achievement_id_idx'), 'userachievement', ['achievement_id'], unique=False)
    op.create_index(op.f('userachievement_user_id_idx'), 'userachievement', ['user_id'], unique=False)
    op.create_table('userquest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quest_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('userquest_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('userquest_pkey'))
    )
    op.create_index(op.f('userquest_quest_id_idx'), 'userquest', ['quest_id'], unique=False)
    op.create_index(op.f('userquest_user_id_idx'), 'userquest', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('userquest_user_id_idx'), table_name='userquest')
    op.drop_index(op.f('userquest_quest_id_idx'), table_name='userquest')
    op.drop_table('userquest')
    op.drop_index(op.f('userachievement_user_id_idx'), table_name='userachievement')
    op.drop_index(op.f('userachievement_achievement_id_idx'), table_name='userachievement')
    op.drop_table('userachievement')
    # ### end Alembic commands ###