"""Add like count to study room

Revision ID: b141fee73d96
Revises: 4767bbe281bc
Create Date: 2026-04-22 10:17:42.997802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b141fee73d96'
down_revision: Union[str, Sequence[str], None] = '4767bbe281bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_room_likes',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['study_rooms.id'], name=op.f('study_room_likes_room_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('study_room_likes_user_id_fkey')),
    sa.PrimaryKeyConstraint('room_id', 'user_id', name=op.f('study_room_likes_pkey'))
    )
    op.create_index(op.f('study_room_likes_room_id_idx'), 'study_room_likes', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('study_room_likes_room_id_idx'), table_name='study_room_likes')
    op.drop_table('study_room_likes')
    # ### end Alembic commands ###