"""Add total xp field to user model

Revision ID: 61175e23b736
Revises: ded2692250e7
Create Date: 2026-04-08 09:40:19.981396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '61175e23b736'
down_revision: Union[str, Sequence[str], None] = 'ded2692250e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('total_xp', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'total_xp')
    # ### end Alembic commands ###