"""Add is active to quest

Revision ID: 82bd0b7ddc97
Revises: b562b9a59cd4
Create Date: 2026-07-16 20:12:11.564007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82bd0b7ddc97'
down_revision: Union[str, Sequence[str], None] = 'b562b9a59cd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'quests', 
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'is_active')
    # ### end Alembic commands ###