"""Add completion date to user achievement

Revision ID: 2e0f625c14d8
Revises: 2f6a48d12cb7
Create Date: 2026-04-08 11:59:48.526584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2e0f625c14d8'
down_revision: Union[str, Sequence[str], None] = '2f6a48d12cb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userachievement', sa.Column('completion_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userachievement', 'completion_date')
    # ### end Alembic commands ###