"""Create eror logging postgres table

Revision ID: 593e2dcb68f0
Revises: 4bb6d5ad0b2e
Create Date: 2026-06-15 21:55:12.759614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '593e2dcb68f0'
down_revision: Union[str, Sequence[str], None] = '4bb6d5ad0b2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('error_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('exception_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('traceback', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('user_role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('error_logs_pkey'))
    )
    op.create_index(op.f('error_logs_exception_type_idx'), 'error_logs', ['exception_type'], unique=False)
    op.create_index(op.f('error_logs_timestamp_idx'), 'error_logs', ['timestamp'], unique=False)
    op.create_index(op.f('error_logs_user_id_idx'), 'error_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('error_logs_user_id_idx'), table_name='error_logs')
    op.drop_index(op.f('error_logs_timestamp_idx'), table_name='error_logs')
    op.drop_index(op.f('error_logs_exception_type_idx'), table_name='error_logs')
    op.drop_table('error_logs')
    # ### end Alembic commands ###