"""Add room id in room chat like for realtime filtering purpose

Revision ID: 6a4af1554ebc
Revises: ee606155f585
Create Date: 2026-05-10 19:50:25.245848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6a4af1554ebc'
down_revision: Union[str, Sequence[str], None] = 'ee606155f585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_chat_likes', sa.Column('room_id', sa.Integer(), nullable=False))
    op.create_index(op.f('room_chat_likes_room_id_idx'), 'room_chat_likes', ['room_id'], unique=False)
    op.create_foreign_key(op.f('room_chat_likes_room_id_fkey'), 'room_chat_likes', 'study_rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('room_chat_likes_room_id_fkey'), 'room_chat_likes', type_='foreignkey')
    op.drop_index(op.f('room_chat_likes_room_id_idx'), table_name='room_chat_likes')
    op.drop_column('room_chat_likes', 'room_id')
    # ### end Alembic commands ###