"""Track quest last progress at

Revision ID: 2744643219fe
Revises: 31b2d48e71df
Create Date: 2026-04-12 19:42:58.411126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2744643219fe'
down_revision: Union[str, Sequence[str], None] = '31b2d48e71df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userquest', sa.Column('last_progress_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userquest', 'last_progress_at')
    # ### end Alembic commands ###