"""Create certificate model

Revision ID: 17f1735c4c95
Revises: c24d79b540b7
Create Date: 2026-04-22 18:49:41.085921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '17f1735c4c95'
down_revision: Union[str, Sequence[str], None] = 'c24d79b540b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('certificates_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('certificates_pkey'))
    )
    op.create_index(op.f('certificates_user_id_idx'), 'certificates', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('certificates_user_id_idx'), table_name='certificates')
    op.drop_table('certificates')
    # ### end Alembic commands ###