"""Move quest definition to db

Revision ID: b562b9a59cd4
Revises: 593e2dcb68f0
Create Date: 2026-07-16 19:48:53.970101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from app.modules.gamification.gamification import QUESTS


# revision identifiers, used by Alembic.
revision: str = 'b562b9a59cd4'
down_revision: Union[str, Sequence[str], None] = '593e2dcb68f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    quests_table = op.create_table(
        'quests',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('event', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('target', sa.Integer(), nullable=False),
        sa.Column('difficulty', sa.String(), nullable=False),
        sa.Column('frequency', sa.String(), nullable=False),
        sa.Column('xp_reward', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('quests_pkey'))
    )
    op.create_index(op.f('quests_id_idx'), 'quests', ['id'], unique=False)

    op.bulk_insert(quests_table, QUESTS)

    op.create_foreign_key(op.f('userquest_quest_id_fkey'), 'userquest', 'quests', ['quest_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('userquest_quest_id_fkey'), 'userquest', type_='foreignkey')
    op.drop_index(op.f('quests_id_idx'), table_name='quests')
    op.drop_table('quests')
    # ### end Alembic commands ###