from app.modules.gamification.schemas import AchievementDef, QuestDef, QuestEvent, QuestFrequency, AchievementType
from app.modules.quiz.schemas import QuizDifficulty


QUESTS: list[QuestDef] = [
    # daily
    {
        "id": "daily_login",
        "title": "Login Harian",
        "description": "Masuk ke aplikasi untuk memulai harimu",
        "event": QuestEvent.USER_LOGIN,
        "target": 1,
        "difficulty": QuizDifficulty.EASY,
        "frequency": QuestFrequency.DAILY,
        "xp_reward": 50,
    },
    {
        "id": "daily_stay_1hour",
        "title": "Fokus belajar selama 1 jam",
        "description": "Tetap di apliksi selama 1 jam",
        "event": QuestEvent.STAY_1_HOUR,
        "target": 1,
        "difficulty": QuizDifficulty.MEDIUM,
        "frequency": QuestFrequency.DAILY,
        "xp_reward": 50,
    },
    {
        "id": "daily_complete_3_task",
        "title": "Selesaikan 3 Tugas",
        "description": "Tandai 3 tugas sebagai selesai di Target dan Tugas",
        "event": QuestEvent.COMPLETE_TASK,
        "target": 3,
        "difficulty": QuizDifficulty.HARD,
        "frequency": QuestFrequency.DAILY,
        "xp_reward": 150,
    },

    # weekly
    {
        "id": "weekly_stay_10hour",
        "title": "Produktif Mingguan",
        "description": "Total 10 jam belajar minggu ini",
        "event": QuestEvent.STAY_10_MIN,
        "target": 60,
        "difficulty": QuizDifficulty.HARD,
        "frequency": QuestFrequency.WEEKLY,
        "xp_reward": 150,
    },
    {
        "id": "weekly_receive_5_like",
        "title": "Kontribusi forum",
        "description": "Dapatkan 5 like dalam forum yang kamu post",
        "event": QuestEvent.RECEIVE_LIKE,
        "target": 5,
        "difficulty": QuizDifficulty.EASY,
        "frequency": QuestFrequency.WEEKLY,
        "xp_reward": 50,
    },
]

ACHIEVEMENTS: list[AchievementDef] = [
    {
        "id": "completed_first_quest",
        "title": "First Step",
        "description": "Selesaikan quest pertama",
        "event": QuestEvent.COMPLETE_QUEST,
        "type": AchievementType.QUEST,
        "target": 1,
        "difficulty": QuizDifficulty.EASY,
        "xp_reward": 100,
    },
    {
        "id": "quest_hunter",
        "title": "Quest Hunter",
        "description": "Selesaikan total 10 quest",
        "event": QuestEvent.COMPLETE_QUEST,
        "type": AchievementType.QUEST,
        "target": 10,
        "difficulty": QuizDifficulty.MEDIUM,
        "xp_reward": 200, 
    },
    {
        "id": "quest_master",
        "title": "Quest Master",
        "description": "Selesaikan total 50 quest",
        "event": QuestEvent.COMPLETE_QUEST,
        "type": AchievementType.QUEST,
        "target": 50,
        "difficulty": QuizDifficulty.HARD,
        "xp_reward": 450,
    },
    {
        "id": "week_warrior",
        "title": "Week Warrior",
        "description": "Login 7 hari berturut-turut",
        "event": QuestEvent.USER_LOGIN_STREAK,
        "type": AchievementType.STREAK,
        "target": 7,
        "difficulty": QuizDifficulty.EASY,
        "xp_reward": 150,
    },
    {
        "id": "month_warrior",
        "title": "Month Warrior",
        "description": "Login 30 hari berturut-turut",
        "event": QuestEvent.USER_LOGIN_STREAK,
        "type": AchievementType.STREAK,
        "target": 30,
        "difficulty": QuizDifficulty.HARD,
        "xp_reward": 500, 
    },
    {
        "id": "rising_star",
        "title": "Rising Star",
        "description": "Dapatkan 10 likes di forum",
        "event": QuestEvent.RECEIVE_LIKE,
        "type": AchievementType.FORUM,
        "target": 10,
        "difficulty": QuizDifficulty.EASY,
        "xp_reward": 100,
    },
    {
        "id": "receive_50_like",
        "title": "Social Star",
        "description": "Dapatkan 50 likes di forum",
        "event": QuestEvent.RECEIVE_LIKE,
        "type": AchievementType.FORUM,
        "target": 50,
        "difficulty": QuizDifficulty.HARD,
        "xp_reward": 300,
    },
    {
        "id": "post_10_comment",
        "title": "Community Helper",
        "description": "Posting 10 komentar di forum",
        "event": QuestEvent.POST_COMMENT,
        "type": AchievementType.FORUM,
        "target": 10,
        "difficulty": QuizDifficulty.MEDIUM,
        "xp_reward": 150,
    },
    # {
    #     "id": "post_30_comment_on_help",
    #     "title": "Top Contributor",
    #     "description": "Posting 30 komentar di forum bantuan",
    #     "event": QuestEvent.POST_COMMENT_ON_HELP,
    #     "type": AchievementType.FORUM,
    #     "target": 30,
    #     "difficulty": QuizDifficulty.HARD,
    #     "xp_reward": 250,
    # },
    {
        "id": "forum_veteran",
        "title": "Forum Veteran",
        "description": "Posting total 100 komentar di forum",
        "event": QuestEvent.POST_COMMENT,
        "type": AchievementType.FORUM,
        "target": 100,
        "difficulty": QuizDifficulty.HARD,
        "xp_reward": 400,
    },
    # {
    #     "id": "altruist",
    #     "title": "The Altruist",
    #     "description": "Posting 50 komentar di kategori bantuan",
    #     "event": QuestEvent.POST_COMMENT_ON_HELP,
    #     "type": AchievementType.FORUM,
    #     "target": 50,
    #     "difficulty": QuizDifficulty.HARD,
    #     "xp_reward": 450, 
    # },
    {
        "id": "task_initiate",
        "title": "Task Initiate",
        "description": "Tandai 10 tugas sebagai selesai di Target dan Tugas",
        "event": QuestEvent.COMPLETE_TASK,
        "type": AchievementType.QUEST,
        "target": 10,
        "difficulty": QuizDifficulty.EASY,
        "xp_reward": 100,
    },
    {
        "id": "task_master",
        "title": "Task Master",
        "description": "Tandai 100 tugas sebagai selesai di Target dan Tugas",
        "event": QuestEvent.COMPLETE_TASK,
        "type": AchievementType.QUEST,
        "target": 100,
        "difficulty": QuizDifficulty.HARD,
        "xp_reward": 500,
    },
]